#!/bin/bash

# PBS script to run gdbtk classify_wf on Wfilter2 #
# 10/12/23 #

#PBS -N Wfilter2_gtdbtk_classify_wf
#PBS -l nodes=1:ppn=24:bigmem
#PBS -q long

# setting path variables

BINS_DIR='/data2/laz2g/metabinner/outs/Wfilter2/binner_outs/Wfilter2/metabinner_res/unitem_profile/kmeans_length_weight_X_t_logtrans_result.tsv_bins/'

OUT_DIR='/data2/laz2g/gtdbtk/outs/Wfilter2/'


source /home/laz2g/miniconda3/etc/profile.d/conda.sh

conda activate

conda activate gtdbtk-2.1.1 

gtdbtk classify_wf --genome_dir $BINS_DIR --out_dir $OUT_DIR --cpus 24 --extension fa

conda deactivate
