#!/bin/bash

# PBS script to run fastp_ QC on Ibir2 raw reads #
# 04/15/22 #

#PBS -N fastp_QC
#PBS -l nodes=1:ppn=12
#PBS -q medium

F_READS_PATH='/data2/laz2g/raw_reads/Ibir2_R1_001.fastq.gz'
R_READS_PATH='/data2/laz2g/raw_reads/Ibir2_R2_001.fastq.gz'
OUT_DIR='/data2/laz2g/fastp_outs/Ibir2'

source /home/laz2g/miniconda3/etc/profile.d/conda.sh

conda activate

conda activate fastp_env 

fastp -i $F_READS_PATH -I $R_READS_PATH -o $OUT_DIR/Ibir2_R1.fastq.gz -O $OUT_DIR/Ibir2_R2.fastq.gz -c -j $OUT_DIR/Ibir2.json -h $OUT_DIR/Ibir2.html --dont_overwrite

conda deactivate
