#!/bin/bash

# PBS script to run fastp_ QC on Acau1 raw reads #
# 04/15/22 #

#PBS -N fastp_QC
#PBS -l nodes=1:ppn=12
#PBS -q medium

F_READS_PATH='/data2/laz2g/raw_reads/Acau1_R1_001.fastq.gz'
R_READS_PATH='/data2/laz2g/raw_reads/Acau1_R2_001.fastq.gz'
OUT_DIR='/data2/laz2g/fastp_outs/Acau1'

source /home/laz2g/miniconda3/etc/profile.d/conda.sh

conda activate

conda activate fastp_env 

fastp -i $F_READS_PATH -I $R_READS_PATH -o $OUT_DIR/Acau1_R1.fastq.gz -O $OUT_DIR/Acau1_R2.fastq.gz -c -j $OUT_DIR/Acau1.json -h $OUT_DIR/Acau1.html --dont_overwrite

conda deactivate
